### ISSUE TITLE
Crash When loading a new world 1.20,1 FORGE

### ISSUE THREAD

**Issue by damikdevil** [txnimc/ImmersiveLanterns#1] opened 2024-10-10 09:29 UTC
[crash-2024-10-10_14.28.03-client.txt](https://github.com/user-attachments/files/17325838/crash-2024-10-10_14.28.03-client.txt)
[latest.log](https://github.com/user-attachments/files/17325840/latest.log)
there's logs and crash report

**Comment by nthxny** [comment] 2024-10-10 09:43
do you have accessories slots disabled in config for some reason? Seems Accessories is failing to find any slots on your player. I’ll publish a fix tomorrow (since it should just silently do nothing and not crash) but this shouldn’t be happening out of the box and seems like something has gone wrong

**Comment by damikdevil** [comment] 2024-10-10 10:19
> do you have accessories slots disabled in config for some reason? Seems Accessories is failing to find any slots on your player. I’ll publish a fix tomorrow (since it should just silently do nothing and not crash) but this shouldn’t be happening out of the box and seems like something has gone wrong

no i dont??

**Comment by damikdevil** [comment] 2024-10-10 10:19
thanks!!

**Comment by nthxny** [comment] 2024-10-10 22:56
should be fixed in latest release, was not able to reproduce though so lmk if issue persists

**Closed by nthxny** 2024-10-10 22:56 UTC
